.TH "HEXSED" 1 "2017-03-29" "Linux User's Manual"


.SH NAME

.P
\fBhexsed\fR \- a stream editor that uses parameters supplied in hex.

.SH SYNOPSIS

.P
\fBhexsed\fR [\-n] [=count]d/find/ filename

.P
\fBhexsed\fR [\-n] [=count]op/find/insert/ filename

.P
where op is one of: i, insert before find string; a, append to find
string; and r, replace the find string.

.P
Where both find and insert must be strings of hex digits expressed
in ASCII. The edited result is sent to \fIstdout\fR.

.P
The optional count if specified will cause editing to quit once the
number of edits performed reaches that count.

.P
\fBhexsed\fR \-[a|e|i|o] char|esc sequence.
Delivers the 2 digit hex ASCII string that represents the input char.

.P
\fBhexsed\fR \-s string

.P
Delivers the 2 didgit hex ASCII string for each byte in string.

.P
\fBhexsed\fR \-u codepoint

.P
Delivers the string of hex bytes representing the utf8 codepoint given.

.SH DESCRIPTION

.P
\fBhexsed\fR writes the edited content of the input file to \fIstdout\fR. If
the hex sequence to find is not found then the output is a copy of the
input. Optionally it will write a count of the deletions or changes.

.SH OPTIONS

.TP
 \fB\-h, \-\-help\fR
print help information and exit.

.TP
 \fB\-a, \-\-ascii\fR
Char. Outputs the 2 digit hex representation of the char input. Must be
a single byte char, use \-\-string for multi\-byte chars.

.TP
 \fB\-e, \-\-escape\fR
\echar. Outputs the 2 digit hex representation of the escape
sequence input. Single byte only after '\e'.

.TP
 \fB\-i, \-\-integer\fR
Decimal digits. Outputs the 2 digit hex representation of the digits input.
Legal range is 0 \- 255, outside range is an error.

.TP
 \fB\-o, \-\-octal\fR
Octal digits. Outputs the 2 digit hex representation of the digits input.
Legal range is 0 \- 377, outside range is an error.

.TP
 \fB\-u, \-\-utf8\fR
Utf8 codepoint in various representations: '<U+nnnn>' where nnnn is
hex codepoint, '&#Xnnnn;' or '&#nnnn;'; hex or decimal representation of
html entity codepoint repectively, or unadorned numbers, 0xnnnn for hex;
0nnnn for octal; or simply nnnn for a decimal number. If the codepoint
number is too large for 4 byte utf8 sequence it's an error.

.TP
 \fB\-s, \-\-string\fR
Null terminated array of bytes. Outputs the 2 digit hex representation
of each byte in the string. Escape sequences like \en, \et may be included.

.TP
 \fB\-n, \-\-edit\-count\fR
Causes the count of applied edits to be output.

.SH AUTHOR

.P
Robert L Parker rlp1938@gmail.com

.\" man code generated by txt2tags 2.6 (http://txt2tags.org)
.\" cmdline: txt2tags -t man hexsed.t2t
